"""Cheering Sign"""
def main():
    '''Cheering Sign'''
    txt1 = input()
    txt2 = input()
    txt3 = input()
    print("************")
    print("* Fighting *")
    print("*%9.8s *"%(txt1))
    print("************")
    print("     ||")
    print("     ||")
    print("     ||")
    print("************")
    print("* Fighting *")
    print("*%9.8s *"%(txt2))
    print("************")
    print("     ||")
    print("     ||")
    print("     ||")
    print("************")
    print("* Fighting *")
    print("*%9.8s *"%(txt3))
    print("************")
    print("     ||")
    print("     ||")
    print("     ||")
main()
