"""Just MAX it V.4"""
def main():
    """Just MAX it V.4"""
    num1 = float(input())
    num2 = float(input())
    num3 = float(input())
    num4 = float(input())
    num5 = float(input())
    num6 = float(input())
    num7 = float(input())
    num8 = float(input())
    num9 = float(input())
    num10 = float(input())
    ans = num1*(num1 > num2)+num2*(num2 >= num1)
    ans = ans*(ans > num3)+num3*(num3 >= ans)
    ans = ans*(ans > num4)+num4*(num4 >= ans)
    ans = ans*(ans > num5)+num5*(num5 >= ans)
    ans = ans*(ans > num6)+num6*(num6 >= ans)
    ans = ans*(ans > num7)+num7*(num7 >= ans)
    ans = ans*(ans > num8)+num8*(num8 >= ans)
    ans = ans*(ans > num9)+num9*(num9 >= ans)
    ans = ans*(ans > num10)+num10*(num10 >= ans)
    print("%.2f"%ans)
main()
